rm(list = ls()) # clears the workspace
rng_seed <- 1
set.seed(rng_seed)


source(here::here("script", "r", "helper_functions.R"))

# Parameters for the simulation study
# ============================================================================ #

n_replicates <- 1000 # number of independent replicates for each configuration and data set
n_particles <- 1000 # number of particles

# Number of smoothing trajectories generated by backward sampling:
n_backward_sampling_particles <- ceiling(n_particles / 2)

n_benchmark_particles <- 150000 # number of particles used by the particle filter used to obtain the "ground truth"
n_benchmark_backward_sampling_particles <- 1000 # number of "backward sampling" particles used to obtain the "ground truth"

# Effective-sample-size threshold for adaptive resampling:
ess_resampling_threshold <- 1.0

# Should filtering distributions be approximated?
approximate_filtering_distributions <- FALSE

# Should ancestor tracing and backward sampling be used?
# Note that this can be costly if n_particles is large.
approximate_smoothing_distributions <- FALSE

# Should the "smoothing weights" from Kviman et al. (2024) be used for
# resampling? Note that if "TRUE" then this induces bias.
use_smoothing_weights <- c(FALSE, TRUE)

# Resampling schemes to use in the simulation study.
resample_types <- c(
  "multinomial",
  "stratified",
  "systematic",
  "variational",
  "variational_alt"#,
#   "multinomial_truncated",
#   "stratified_truncated",
#   "systematic_truncated"
)

# Addition for the file names.
filename_addendum <- paste0(
  "_real_data",
  "_n_replicates_", n_replicates,
  "_n_particles_", n_particles,
  "_n_backward_sampling_particles_", n_backward_sampling_particles,
  "_n_benchmark_particles_", n_benchmark_particles,
  "_n_benchmark_backward_sampling_particles_", n_benchmark_backward_sampling_particles,
  "_rng_seed_", rng_seed
)

simulate_data <- FALSE # if TRUE, then the results are re-generated; if FALSE, then the saved .Rds results are used

if (simulate_data) {

  # The data set
  # ============================================================================ #

  # NOTE: Yahoo Finance is now paywalled. Therefore the data was downloaded
  # from https://www.kaggle.com/datasets/henryhan117/sp-500-historical-data

  # NOTE: In Kviman et al. (2024), the log returns are detrended by taking first
  # differences /of the log returns/. This does not seem to be appropriate for
  # the stochastic volatility model as it models log returns not the first
  # differences of the log returns. However, to reproduce their results, we
  # also take such first-order differences here.

  read_csv(here::here("data", "spx", "spx.csv")) %>%
    filter(Date >= "2006-04-03" & Date <= "2014-03-31") %>%
    pull(Close) %>%
    log() %>% # obtains log-closing prices
    diff() %>% # obtains log-returns
  #   subtract(mean(.)) %>% # detrending by subtracting the mean (NOTE: this would be standard practice)
    diff() %>% # detrending by taking first-order differences (NOTE: this reproduces the coding error in Kviman et al. (2024)
    as.matrix() %>%
    t() -> observations




  # The model parameters
  # ============================================================================ #

  # The parameters found via the grid search in Kviman et al. (2024). Note that
  # these were found based on the erroneously computed observations mentioned
  # above.

  phi <- 0.8
  sigma <- 1
  beta <- 0.01

  # The simulation study
  # ============================================================================ #

  run_simulation_study_stochastic_volatility_model_real_data_cpp(
    observations,
    phi,
    sigma,
    beta,
    n_replicates,
    n_particles,
    n_backward_sampling_particles,
    n_benchmark_particles,
    n_benchmark_backward_sampling_particles,
    ess_resampling_threshold,
    use_smoothing_weights,
    resample_types,
    approximate_filtering_distributions,
    approximate_smoothing_distributions,
    rng_seed
  ) %>%
    as_tibble() -> results

  # For rng_seed = 1, the benchmark particle filter with 100000 particles and stratified resampling
  # estimates the "ground truth" likelihood as 5473.36; with 150000 particles it is 5473.27.
  # This is substantially higher than the 5469.39 "ground truth" found by the benchmark particle filter
  # with 50000 particles and multinomial resampling used in Kviman et al. (2024).

  results %>%
    write_rds(here::here("data", "stochastic_volatility_model", paste0("results", filename_addendum, ".Rds")))
  # rm(results)

} else {
  filename_addendum <- "_real_data_n_replicates_1000_n_particles_1000_n_backward_sampling_particles_500_n_benchmark_particles_150000_n_benchmark_backward_sampling_particles_1000_rng_seed_1"
  results <- read_rds(here::here("data", "stochastic_volatility_model", paste0("results", filename_addendum, ".Rds")))
}

results %>%
  filter(metric == "relative_likelihood_estimation_error") %>%
  mutate(
    resample_type_cat = case_when(
      resample_type == resample_types[1] ~ resample_type_names[1],
      resample_type == resample_types[2] ~ resample_type_names[2],
      resample_type == resample_types[3] ~ resample_type_names[3],
      resample_type == resample_types[4] ~ resample_type_names[4],
      resample_type == resample_types[5] ~ resample_type_names[5],
      TRUE ~ resample_type
    )
  ) %>%
  mutate(
    resample_type_cat = factor(
      resample_type_cat,
      levels = resample_type_names
    )
  ) %>%
  mutate(use_smoothing_weights = if_else(use_smoothing_weights, "smoothing weights", "standard weights")) %>%
  mutate(
    use_smoothing_weights = factor(
      use_smoothing_weights,
      levels = c("standard weights", "smoothing weights")
    )
  ) %>%
  filter(metric == "relative_likelihood_estimation_error") %>%
  ggplot(mapping = aes(y = resample_type_cat, x = value + 1, colour = resample_type_cat, fill = resample_type_cat)) + # the "+1" is needed because we have stored $\hat{Z}/Z - 1$
  geom_boxplot(
    show.legend = FALSE,
    alpha = alpha_fill_default
  ) +
  geom_vline(linetype = "dashed", xintercept = 1) +
  theme_classic(base_size = base_size_default) +
  coord_cartesian(xlim = c(0, 100)) +
  labs(y = "Resampling scheme", x = "Relative likelihood estimate") +
  facet_grid(rows = vars(use_smoothing_weights)) +
  scale_colour_manual(breaks = resample_type_names, values = resample_type_colours) +
  scale_fill_manual(breaks = resample_type_names, values = resample_type_colours) +
  scale_x_continuous(labels = scales::comma) +
  scale_y_discrete(limits = rev, labels = scales::label_wrap(10)) -> p_likelihood_estimates_real_data


  p_likelihood_estimates_real_data %>% save_figure(fig_name = "likelihood_estimates_real_data", height = 3)




results %>%
  filter(metric == "relative_likelihood_estimation_error") %>%
  mutate(
    resample_type_cat = case_when(
      resample_type == resample_types[1] ~ resample_type_names[1],
      resample_type == resample_types[2] ~ resample_type_names[2],
      resample_type == resample_types[3] ~ resample_type_names[3],
      resample_type == resample_types[4] ~ resample_type_names[4],
      resample_type == resample_types[5] ~ resample_type_names[5],
      TRUE ~ resample_type
    )
  ) %>%
  mutate(
    resample_type_cat = factor(
      resample_type_cat,
      levels = resample_type_names
    )
  ) %>%
  mutate(use_smoothing_weights = if_else(use_smoothing_weights, "smoothing weights", "standard weights")) %>%
  mutate(
    use_smoothing_weights = factor(
      use_smoothing_weights,
      levels = c("standard weights", "smoothing weights")
    )
  ) %>%
  ggplot(mapping = aes(x = resample_type_cat, y = log(value + 1) + 5473.27)) +
  geom_boxplot() +
  geom_hline(yintercept = 5473.27, linetype = "dashed") +
  theme_classic() +
  facet_wrap(~use_smoothing_weights)



results %>%
mutate(
    resample_type_cat = case_when(
      resample_type == resample_types[1] ~ resample_type_names[1],
      resample_type == resample_types[2] ~ resample_type_names[2],
      resample_type == resample_types[3] ~ resample_type_names[3],
      resample_type == resample_types[4] ~ resample_type_names[4],
      resample_type == resample_types[5] ~ resample_type_names[5],
      TRUE ~ resample_type
    )
  ) %>%
  mutate(
    resample_type_cat = factor(
      resample_type_cat,
      levels = resample_type_names
    )
  ) %>%
  mutate(use_smoothing_weights = if_else(use_smoothing_weights, "smoothing weights", "standard weights")) %>%
  mutate(
    use_smoothing_weights = factor(
      use_smoothing_weights,
      levels = c("standard weights", "smoothing weights")
    )
  ) %>%
  filter(metric == "relative_likelihood_estimation_error") %>%
  mutate(relative_estimate = value + 1) %>%
  mutate(log_estimate = log(relative_estimate) + 5473.27) %>%
  select(resample_type_cat, use_smoothing_weights, log_estimate, relative_estimate) %>%
  pivot_longer(c(log_estimate, relative_estimate), names_to = "type", values_to = "value") %>%
  group_by(resample_type_cat, use_smoothing_weights, type) %>%
  reframe(mean = mean(value), median = median(value), sd = sd(value)) %>%
  arrange(use_smoothing_weights, type) %>%
  rename("Resampling weights" = "use_smoothing_weights") %>%
  rename("Resampling scheme" = "resample_type_cat") -> results_table


n_decimal_places <- 2

results_table %>%
  filter(type == "log_estimate") %>%
  mutate(
    mean = format(round(mean, digits = n_decimal_places), nsmall = n_decimal_places),
    sd = paste0("($\\pm$", format(round(sd, digits = n_decimal_places), nsmall = n_decimal_places), ")")
  ) %>%
  mutate(`Resampling scheme` = as.character(`Resampling scheme`)) %>%
  select(!c(median, type)) %>%
  unite("This work ($\\pm$std\\,dev.)", c(mean, sd), sep = " ")   %>%
  bind_rows(
    tibble(
      `Resampling scheme` = "Ground truth",
      `Resampling weights` = "",
      `This work ($\\pm$std\\,dev.)` = "5473.36"
    )
  ) %>%
  bind_cols(
    tibble(
      `Kviman et al. (2024)` = c("", 5468.77, "", 5473.37, "", "", "", "", 5470.68, "", 5469.39)
    )
  ) %>%
  xtable::xtable(type = "latex") %>%
  print(include.rownames = FALSE, sanitize.text.function = function(x){x})


results %>%
mutate(
    resample_type_cat = case_when(
      resample_type == resample_types[1] ~ resample_type_names[1],
      resample_type == resample_types[2] ~ resample_type_names[2],
      resample_type == resample_types[3] ~ resample_type_names[3],
      resample_type == resample_types[4] ~ resample_type_names[4],
      resample_type == resample_types[5] ~ resample_type_names[5],
      TRUE ~ resample_type
    )
  ) %>%
  mutate(
    resample_type_cat = factor(
      resample_type_cat,
      levels = resample_type_names
    )
  ) %>%
  mutate(use_smoothing_weights = if_else(use_smoothing_weights, "smoothing weights", "standard weights")) %>%
  mutate(
    use_smoothing_weights = factor(
      use_smoothing_weights,
      levels = c("standard weights", "smoothing weights")
    )
  ) %>%
  filter(metric == "relative_likelihood_estimation_error") %>%
  mutate(relative_estimate = value + 1) %>%
  mutate(log_relative_estimate = log(relative_estimate)) %>%
  select(resample_type_cat, use_smoothing_weights, log_relative_estimate, relative_estimate) %>%
  pivot_longer(3:4, names_to = "type", values_to = "value") %>%
  group_by(resample_type_cat, use_smoothing_weights, type) %>%
  reframe(mean = mean(value), median = median(value), sd = sd(value)) %>%
  arrange(use_smoothing_weights, type) %>%
  rename("Resampling weights" = "use_smoothing_weights") %>%
  rename("Resampling scheme" = "resample_type_cat") %>%
  rename("Estimate" = "type", "Mean" = "mean", "Median" = "median", "Std dev." = "sd") %>%
  xtable::xtable(type = "latex") %>%
  print(include.rownames = FALSE, sanitize.text.function = function(x){x})


