rm(list = ls()) # clears the workspace
rng_seed <- 1
set.seed(rng_seed)


source(here::here("script", "r", "helper_functions.R"))

# Parameters for the simulation study
# ============================================================================ #

n_replicates <- 20 # number of independent replicates for each configuration and data set
n_data_sets <- 20 # number of independent data sets sampled from the model
n_observations <- 50 # number of observations
n_particles <- 1000 # number of particles

# Number of smoothing trajectories generated by backward sampling:
n_backward_sampling_particles <- ceiling(n_particles / 2)

n_benchmark_particles <- 20000 # number of particles used by the particle filter used to obtain the "ground truch"
n_benchmark_backward_sampling_particles <- 1000 # number of "backward sampling" particles used to obtain the "ground truth"

# Effective-sample-size threshold for adaptive resampling:
ess_resampling_threshold <- 1.0

# Should the "smoothing weights" from Kviman et al. (2024) be used for
# resampling? Note that if "TRUE" then this induces bias.
use_smoothing_weights <- c(FALSE, TRUE)

# Resampling schemes to use in the simulation study.
resample_types <- c(
  "multinomial",
  "stratified",
  "systematic",
  "variational",
  "variational_alt"#,
#   "multinomial_truncated",
#   "stratified_truncated",
#   "systematic_truncated"
)

# Addition for the file names.
filename_addendum <- paste0(
  "_n_replicates_", n_replicates,
  "_n_data_sets_", n_data_sets,
  "_n_observations_", n_observations,
  "_n_particles_", n_particles,
  "_n_backward_sampling_particles_", n_backward_sampling_particles,
  "_rng_seed_", rng_seed
)



# Runs the simulation study for the linear-Gaussian state-space model
# ============================================================================ #
run_simulation_study_linear_gaussian_state_space_model_cpp(
  n_data_sets,
  n_replicates,
  n_observations,
  n_particles,
  n_backward_sampling_particles,
  n_benchmark_particles,
  n_benchmark_backward_sampling_particles,
  ess_resampling_threshold,
  use_smoothing_weights,
  resample_types,
  rng_seed
) %>%
  as_tibble() -> results

results %>%
  write_rds(here::here("data", "linear_gaussian_state_space_model", paste0("results", filename_addendum, ".Rds")))
rm(results)



# Runs the simulation study for the stochastic volatility model
# ============================================================================ #

run_simulation_study_stochastic_volatility_model_cpp(
  n_data_sets,
  n_replicates,
  n_observations,
  n_particles,
  n_backward_sampling_particles,
  n_benchmark_particles,
  n_benchmark_backward_sampling_particles,
  ess_resampling_threshold,
  use_smoothing_weights,
  resample_types,
  rng_seed
) %>%
  as_tibble() -> results

results %>%
  write_rds(here::here("data", "stochastic_volatility_model", paste0("results", filename_addendum, ".Rds")))
rm(results)


# Runs the simulation study for the nonlinear state-space model
# ============================================================================ #

run_simulation_study_nonlinear_state_space_model_cpp(
  n_data_sets,
  n_replicates,
  n_observations,
  n_particles,
  n_backward_sampling_particles,
  n_benchmark_particles,
  n_benchmark_backward_sampling_particles,
  ess_resampling_threshold,
  use_smoothing_weights,
  resample_types,
  rng_seed
) %>%
  as_tibble() -> results

results %>%
  write_rds(here::here("data", "nonlinear_state_space_model", paste0("results", filename_addendum, ".Rds")))
rm(results)


# Runs the simulation study for the Lorenz-63 state-space model
# ============================================================================ #

run_simulation_study_lorenz_state_space_model_cpp(
  n_data_sets,
  n_replicates,
  n_observations,
  n_particles,
  n_backward_sampling_particles,
  n_benchmark_particles,
  n_benchmark_backward_sampling_particles,
  ess_resampling_threshold,
  use_smoothing_weights,
  resample_types,
  rng_seed
) %>%
  as_tibble() -> results

results %>%
  write_rds(here::here("data", "lorenz_state_space_model", paste0("results", filename_addendum, ".Rds")))
rm(results)
